<a href="https://colab.research.google.com/github/akriti0810/tips-analysis/blob/main/tips_analysis_sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)

In [2]:
conn = sqlite3.connect(":memory:")
df.to_sql("tips", conn, index=False)

244

In [3]:
query = "SELECT * FROM tips LIMIT 5"
pd.read_sql(query, conn)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
query = "SELECT * FROM tips WHERE day = 'Sun'"
pd.read_sql(query, conn)

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
..         ...   ...     ...    ...  ...     ...   ...
71       20.90  3.50  Female    Yes  Sun  Dinner     3
72       30.46  2.00    Male    Yes  Sun  Dinner     5
73       18.15  3.50  Female    Yes  Sun  Dinner     3
74       23.10  4.00    Male    Yes  Sun  Dinner     3
75       15.69  1.50    Male    Yes  Sun  Dinner     2

[76 rows x 7 columns]

In [6]:
query = """
SELECT day, AVG(tip / total_bill * 100) as avg_tip_pct
FROM tips
GROUP BY day
"""
pd.read_sql(query, conn)

    day  avg_tip_pct
0   Fri    16.991303
1   Sat    15.315172
2   Sun    16.689729
3  Thur    16.127563

In [7]:
query = """
SELECT day, AVG(tip / total_bill * 100) as avg_tip_pct
FROM tips
GROUP BY day
ORDER BY avg_tip_pct DESC
"""
pd.read_sql(query, conn)

    day  avg_tip_pct
0   Fri    16.991303
1   Sun    16.689729
2  Thur    16.127563
3   Sat    15.315172

In [8]:
query = """
SELECT day, AVG(tip / total_bill * 100) as avg_tip_pct
FROM tips
GROUP BY day
HAVING avg_tip_pct > 16
ORDER BY avg_tip_pct DESC
"""
pd.read_sql(query, conn)

    day  avg_tip_pct
0   Fri    16.991303
1   Sun    16.689729
2  Thur    16.127563